### ISSUE TITLE
How to download the translated cc dataset?

### ISSUE THREAD

**Issue by BUAADreamer** [danoneata/td-mml#1]
When I click the link, I got this:
![image](https://user-images.githubusercontent.com/64362896/204131681-af087575-82f1-4742-a646-6de60e10a454.png)

What are the username and password?

**Comment by danoneata** [comment]
Hello @BUAADreamer! I've inserted the wrong link in the README—apologies for that! The correct link is [the following](https://sharing.speed.pub.ro/owncloud/index.php/s/PyFrJT0uVxyoxFI); I've also updated the README. Thank you for pointing this out!

**Comment by BUAADreamer** [comment]
Thanks for adjusting this so quickly! I will try and tell whether it works.

**Comment by BUAADreamer** [comment]
Thanks very much!!!this link works
However, I want to ask whether you have all or most of pictures of cc3m(like 2.7M). If so, can you give a access link too? Because I find that at least 1M cc3m'pic link doesn't work, and lack of pics may lead to the difficulty of reproduction.
If the pics'size is too large, I can pay for some fee you use to upload them!😁

**Comment by danoneata** [comment]
For this project we have used the pre-extracted features from VOLTA available [here](https://github.com/e-bug/volta/tree/main/data). Would these work for you as well?

**Comment by BUAADreamer** [comment]
> For this project we have used the pre-extracted features from VOLTA available [here](https://github.com/e-bug/volta/tree/main/data). Would these work for you as well?

As I use ViT, this may be useless. Anyway, Thank you very much, for this excellent paper and quick reply!
